# Generated by Django 4.2.2 on 2024-02-28 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_order_state_order_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='orders',
        ),
        migrations.DeleteModel(
            name='cart',
        ),
    ]
