# Generated by Django 4.2.2 on 2024-03-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='alaa',
            field=models.IntegerField(default=1),
        ),
    ]
