# Generated by Django 4.2.2 on 2024-03-01 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_cart_alaa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='user1',
        ),
    ]
