# Generated by Django 4.2.2 on 2024-03-01 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_rename_user1_cart_user_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_cart',
            new_name='user',
        ),
    ]
