# Generated by Django 4.2.2 on 2024-03-01 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_rename_user_cart_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='Cart',
            new_name='cart',
        ),
    ]
