# Generated by Django 4.2.2 on 2024-03-01 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_orderitem_order_alter_orderitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='alaa',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='esraa',
        ),
    ]
