# Generated by Django 4.2.2 on 2024-03-03 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_alter_orderitem_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=30),
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Processing', max_length=60),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cart_ddd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.cart'),
        ),
    ]
