# Generated by Django 4.2.2 on 2024-03-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_remove_orderitem_cart_cart_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
    ]
