# Generated by Django 4.2.2 on 2024-03-03 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_remove_order_payment_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='cart_ddd',
        ),
    ]
