# Generated by Django 4.2.2 on 2024-03-03 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
